# Generated by Django 4.0.3 on 2022-04-08 02:28

import birthday.fields
from django.db import migrations, models
import django.db.models.deletion
import gestionviajes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('capacidad', models.IntegerField(blank=True, default='10', max_length=40, null=True, verbose_name='Capacidad')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=10, verbose_name='Apellido')),
                ('dni', models.IntegerField(max_length=10, verbose_name='DNI')),
                ('genero', models.CharField(choices=[('maculino', 'Masculino'), ('femenino', 'Femenino')], max_length=30, verbose_name='Genero')),
                ('fecha_nacimiento_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('fecha_nacimiento', birthday.fields.BirthdayField()),
            ],
        ),
        migrations.CreateModel(
            name='PasajeroBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.IntegerField(max_length=10)),
                ('bus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionviajes.bus')),
                ('pasajero', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionviajes.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reserva', models.CharField(default=gestionviajes.models.generar_numero_reserva, editable=False, max_length=100)),
                ('estatus', models.BooleanField(default=True)),
                ('pasajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionviajes.pasajerobus')),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=10, verbose_name='Apellido')),
                ('dni', models.IntegerField(max_length=10, verbose_name='DNI')),
                ('genero', models.CharField(choices=[('maculino', 'Masculino'), ('femenino', 'Femenino')], max_length=30, verbose_name='Genero')),
                ('fecha_nacimiento_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('fecha_nacimiento', birthday.fields.BirthdayField()),
                ('bus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chofer_bus', to='gestionviajes.bus')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_horario', to='gestionviajes.horario'),
        ),
        migrations.AddField(
            model_name='bus',
            name='trayecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_trayecto', to='gestionviajes.trayecto'),
        ),
    ]
